name: Run Appium Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  appium-tests:
    runs-on: ubuntu-latest

    services:
      appium:
        image: appium/appium
        ports:
          - 4723:4723
        options: >-
          --health-cmd "curl -f http://localhost:4723/status || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Install Java (required for Android SDK)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: default
          arch: x86_64          
          force-avd-creation: true
          script: echo "Emulator is ready"


      - name: Build project
        run: dotnet build AppiumTests/AppiumTests.csproj --configuration Release

      - name: Run tests
        run: dotnet test AppiumTests/AppiumTests.csproj --configuration Release --logger "trx"
